// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK4sHZoHu62vB5DvhVkjdhNfVHS7Eguus',
    appId: '1:276354321693:web:08bf8dd83af8bddf6565f4',
    messagingSenderId: '276354321693',
    projectId: 'authexample1-8b31e',
    authDomain: 'authexample1-8b31e.firebaseapp.com',
    storageBucket: 'authexample1-8b31e.firebasestorage.app',
    measurementId: 'G-HYCPKS7WGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5c9m8g9Awm2CkSnNHrmS-ZffY11w_7zM',
    appId: '1:276354321693:android:83510ee3eb4bee256565f4',
    messagingSenderId: '276354321693',
    projectId: 'authexample1-8b31e',
    storageBucket: 'authexample1-8b31e.firebasestorage.app',
  );
}
